[package]
name = "jellyfin-controller"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
chrono.workspace = true
jellyfin-data = { path = "../jellyfin-data" }
jellyfin-drawing = { path = "../jellyfin-drawing" }
jellyfin-extensions = { path = "../jellyfin-extensions" }
jellyfin-media-encoding = { path = "../jellyfin-media-encoding" }
jellyfin-model = { path = "../jellyfin-model" }
jellyfin-naming = { path = "../jellyfin-naming" }
jellyfin-providers = { path = "../jellyfin-providers" }
md-5 = "0.10"
notify.workspace = true
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
sea-orm.workspace = true
serde.workspace = true
serde_json.workspace = true
sysinfo.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["fs", "io-util", "time"] }
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true

[lints]
workspace = true
