use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .get_connection()
            .execute_unprepared(
                r"
                CREATE TABLE IF NOT EXISTS jellyfin.quick_connect_requests (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    code varchar(6) NOT NULL,
                    secret varchar(64) NOT NULL,
                    device_id varchar(256) NOT NULL,
                    device_name varchar(64) NOT NULL,
                    app_name varchar(64) NOT NULL,
                    app_version varchar(32) NOT NULL,
                    created_at timestamptz NOT NULL,
                    expires_at timestamptz NOT NULL,
                    authorized_at timestamptz,
                    user_id uuid,
                    authorized_device_id bigint,
                    CONSTRAINT quick_connect_code_format
                        CHECK (code ~ '^[0-9]{6}$'),
                    CONSTRAINT quick_connect_secret_format
                        CHECK (secret ~ '^[0-9A-Fa-f]{64}$'),
                    CONSTRAINT quick_connect_device_id_not_empty
                        CHECK (device_id <> ''),
                    CONSTRAINT quick_connect_device_name_not_empty
                        CHECK (device_name <> ''),
                    CONSTRAINT quick_connect_app_name_not_empty
                        CHECK (app_name <> ''),
                    CONSTRAINT quick_connect_app_version_not_empty
                        CHECK (app_version <> ''),
                    CONSTRAINT quick_connect_expiry_after_creation
                        CHECK (expires_at > created_at),
                    CONSTRAINT quick_connect_authorization_consistent CHECK (
                        (authorized_at IS NULL AND user_id IS NULL AND authorized_device_id IS NULL)
                        OR
                        (authorized_at IS NOT NULL AND user_id IS NOT NULL AND authorized_device_id IS NOT NULL)
                    ),
                    CONSTRAINT quick_connect_user_id_fkey
                        FOREIGN KEY (user_id) REFERENCES jellyfin.users (id) ON DELETE CASCADE,
                    CONSTRAINT quick_connect_authorized_device_id_fkey
                        FOREIGN KEY (authorized_device_id) REFERENCES jellyfin.devices (id) ON DELETE CASCADE
                );
                CREATE UNIQUE INDEX IF NOT EXISTS quick_connect_code_key
                    ON jellyfin.quick_connect_requests (code);
                CREATE UNIQUE INDEX IF NOT EXISTS quick_connect_secret_key
                    ON jellyfin.quick_connect_requests (secret);
                CREATE INDEX IF NOT EXISTS quick_connect_expires_at_idx
                    ON jellyfin.quick_connect_requests (expires_at);
                DROP INDEX IF EXISTS jellyfin.quick_connect_authorized_secret_idx;
                CREATE INDEX IF NOT EXISTS quick_connect_authorized_device_id_idx
                    ON jellyfin.quick_connect_requests (authorized_device_id)
                    WHERE authorized_device_id IS NOT NULL;
                ",
            )
            .await?;
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .get_connection()
            .execute_unprepared("DROP TABLE IF EXISTS jellyfin.quick_connect_requests CASCADE;")
            .await?;
        Ok(())
    }
}
