use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .get_connection()
            .execute_unprepared(
                r"
                CREATE TABLE IF NOT EXISTS jellyfin.emby_camera_uploads (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    device_id varchar(256) NOT NULL,
                    upload_id varchar(1024) NOT NULL,
                    name varchar(512) NOT NULL,
                    album varchar(512) NOT NULL DEFAULT '',
                    mime_type varchar(255),
                    date_created timestamptz,
                    stored_path text NOT NULL,
                    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
                    CONSTRAINT emby_camera_uploads_device_id_not_empty CHECK (device_id <> ''),
                    CONSTRAINT emby_camera_uploads_upload_id_not_empty CHECK (upload_id <> ''),
                    CONSTRAINT emby_camera_uploads_name_not_empty CHECK (name <> ''),
                    CONSTRAINT emby_camera_uploads_stored_path_not_empty CHECK (stored_path <> '')
                );

                CREATE INDEX IF NOT EXISTS emby_camera_uploads_device_order_idx
                    ON jellyfin.emby_camera_uploads (lower(device_id), id);

                COMMENT ON TABLE jellyfin.emby_camera_uploads IS
                    'Private Emby reported-device camera upload history, retained across users and device-auth deletion.';
                ",
            )
            .await?;
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .get_connection()
            .execute_unprepared("DROP TABLE IF EXISTS jellyfin.emby_camera_uploads CASCADE;")
            .await?;
        Ok(())
    }
}
