use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .get_connection()
            .execute_unprepared(
                r"
                CREATE TABLE IF NOT EXISTS jellyfin.display_preferences (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id uuid NOT NULL,
                    item_id uuid NOT NULL,
                    client varchar(128) NOT NULL,
                    preferences jsonb NOT NULL DEFAULT '{}'::jsonb,
                    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
                    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
                    CONSTRAINT display_preferences_user_id_fkey
                        FOREIGN KEY (user_id) REFERENCES jellyfin.users (id) ON DELETE CASCADE,
                    CONSTRAINT display_preferences_client_not_empty CHECK (client <> ''),
                    CONSTRAINT display_preferences_preferences_object
                        CHECK (jsonb_typeof(preferences) = 'object')
                );
                CREATE UNIQUE INDEX IF NOT EXISTS display_preferences_user_item_client_key
                    ON jellyfin.display_preferences (user_id, item_id, client);
                CREATE INDEX IF NOT EXISTS display_preferences_user_client_idx
                    ON jellyfin.display_preferences (user_id, client, updated_at DESC);
                CREATE INDEX IF NOT EXISTS display_preferences_preferences_gin_idx
                    ON jellyfin.display_preferences USING gin (preferences jsonb_path_ops);
                ",
            )
            .await?;
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .get_connection()
            .execute_unprepared("DROP TABLE IF EXISTS jellyfin.display_preferences CASCADE;")
            .await?;
        Ok(())
    }
}
