use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .get_connection()
            .execute_unprepared(
                r"
                CREATE TABLE IF NOT EXISTS jellyfin.device_options (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    device_id varchar(256) NOT NULL,
                    custom_name text,
                    CONSTRAINT device_options_device_id_not_empty CHECK (device_id <> '')
                );
                CREATE UNIQUE INDEX IF NOT EXISTS device_options_device_id_key
                    ON jellyfin.device_options (device_id) INCLUDE (custom_name);
                ",
            )
            .await?;
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .get_connection()
            .execute_unprepared(
                r"
                DROP TABLE IF EXISTS jellyfin.device_options CASCADE;
                ",
            )
            .await?;
        Ok(())
    }
}
