use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .get_connection()
            .execute_unprepared(
                r"
                ALTER TABLE jellyfin.item_values
                    ADD COLUMN IF NOT EXISTS emby_id bigint
                    GENERATED BY DEFAULT AS IDENTITY;

                CREATE UNIQUE INDEX IF NOT EXISTS item_values_emby_id_key
                    ON jellyfin.item_values (emby_id);

                COMMENT ON COLUMN jellyfin.item_values.emby_id IS
                    'Stable numeric identifier for Emby NameLongIdPair wire contracts.';
                ",
            )
            .await?;
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .get_connection()
            .execute_unprepared(
                "DROP INDEX IF EXISTS jellyfin.item_values_emby_id_key; \
                 ALTER TABLE jellyfin.item_values DROP COLUMN IF EXISTS emby_id;",
            )
            .await?;
        Ok(())
    }
}
