use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .get_connection()
            .execute_unprepared(
                r"
                CREATE TABLE IF NOT EXISTS jellyfin.password_resets (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username_hash char(32) NOT NULL,
                    user_id uuid NOT NULL,
                    user_name varchar(255) NOT NULL,
                    pin varchar(11) NOT NULL,
                    pin_compact char(8) NOT NULL,
                    pin_file varchar(512) NOT NULL,
                    created_at timestamptz NOT NULL,
                    expires_at timestamptz NOT NULL,
                    CONSTRAINT password_resets_user_id_fkey
                        FOREIGN KEY (user_id) REFERENCES jellyfin.users (id) ON DELETE CASCADE,
                    CONSTRAINT password_resets_username_hash_format
                        CHECK (username_hash ~ '^[0-9a-f]{32}$'),
                    CONSTRAINT password_resets_user_name_not_empty
                        CHECK (user_name <> ''),
                    CONSTRAINT password_resets_pin_format
                        CHECK (pin ~ '^[0-9A-F]{2}(-[0-9A-F]{2}){3}$'),
                    CONSTRAINT password_resets_pin_compact_format
                        CHECK (pin_compact ~ '^[0-9A-F]{8}$'),
                    CONSTRAINT password_resets_pin_file_not_empty
                        CHECK (pin_file <> ''),
                    CONSTRAINT password_resets_expiry_after_creation
                        CHECK (expires_at > created_at)
                );
                CREATE UNIQUE INDEX IF NOT EXISTS password_resets_username_hash_key
                    ON jellyfin.password_resets (username_hash);
                CREATE INDEX IF NOT EXISTS password_resets_pin_lookup_idx
                    ON jellyfin.password_resets (pin_compact, expires_at);
                CREATE INDEX IF NOT EXISTS password_resets_expires_at_idx
                    ON jellyfin.password_resets (expires_at);
                ",
            )
            .await?;
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .get_connection()
            .execute_unprepared("DROP TABLE IF EXISTS jellyfin.password_resets CASCADE;")
            .await?;
        Ok(())
    }
}
