use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .get_connection()
            .execute_unprepared(
                r"
                CREATE TABLE IF NOT EXISTS jellyfin.activity_logs (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name varchar(512) NOT NULL,
                    overview varchar(512),
                    short_overview varchar(512),
                    activity_type varchar(256) NOT NULL,
                    user_id uuid NOT NULL,
                    item_id varchar(256),
                    date_created timestamptz NOT NULL DEFAULT clock_timestamp(),
                    log_severity smallint NOT NULL DEFAULT 2,
                    row_version bigint NOT NULL DEFAULT 1,
                    CONSTRAINT activity_logs_name_not_empty CHECK (name <> ''),
                    CONSTRAINT activity_logs_type_not_empty CHECK (activity_type <> ''),
                    CONSTRAINT activity_logs_severity_range CHECK (log_severity BETWEEN 0 AND 6)
                );

                CREATE INDEX IF NOT EXISTS activity_logs_date_created_brin_idx
                    ON jellyfin.activity_logs USING brin (date_created)
                    WITH (pages_per_range = 32, autosummarize = on);
                CREATE INDEX IF NOT EXISTS activity_logs_item_id_idx
                    ON jellyfin.activity_logs (item_id)
                    WHERE item_id IS NOT NULL;

                CREATE OR REPLACE FUNCTION jellyfin.touch_activity_log_row_version()
                RETURNS trigger LANGUAGE plpgsql AS $function$
                BEGIN
                    NEW.row_version := OLD.row_version + 1;
                    RETURN NEW;
                END
                $function$;

                DROP TRIGGER IF EXISTS activity_logs_touch_row_version
                    ON jellyfin.activity_logs;
                CREATE TRIGGER activity_logs_touch_row_version
                    BEFORE UPDATE ON jellyfin.activity_logs
                    FOR EACH ROW
                    EXECUTE FUNCTION jellyfin.touch_activity_log_row_version();
                ",
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .get_connection()
            .execute_unprepared(
                r"
                DROP TABLE IF EXISTS jellyfin.activity_logs CASCADE;
                DROP FUNCTION IF EXISTS jellyfin.touch_activity_log_row_version();
                ",
            )
            .await?;
        Ok(())
    }
}
