use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .get_connection()
            .execute_unprepared(
                r"
                CREATE TABLE IF NOT EXISTS jellyfin.api_keys (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    date_created timestamptz NOT NULL DEFAULT clock_timestamp(),
                    date_last_activity timestamptz NOT NULL DEFAULT clock_timestamp(),
                    name varchar(64) NOT NULL,
                    access_token varchar(128) NOT NULL,
                    CONSTRAINT api_keys_name_not_empty CHECK (name <> '')
                );
                CREATE UNIQUE INDEX IF NOT EXISTS api_keys_access_token_key
                    ON jellyfin.api_keys (access_token);

                CREATE TABLE IF NOT EXISTS jellyfin.devices (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id uuid NOT NULL,
                    access_token varchar(128) NOT NULL,
                    app_name varchar(64) NOT NULL,
                    app_version varchar(32) NOT NULL,
                    device_name varchar(64) NOT NULL,
                    device_id varchar(256) NOT NULL,
                    is_active boolean NOT NULL DEFAULT false,
                    capabilities jsonb NOT NULL DEFAULT '{}'::jsonb,
                    date_created timestamptz NOT NULL DEFAULT clock_timestamp(),
                    date_modified timestamptz NOT NULL DEFAULT clock_timestamp(),
                    date_last_activity timestamptz NOT NULL DEFAULT clock_timestamp(),
                    CONSTRAINT devices_user_id_fkey
                        FOREIGN KEY (user_id) REFERENCES jellyfin.users (id) ON DELETE CASCADE,
                    CONSTRAINT devices_device_id_not_empty CHECK (device_id <> ''),
                    CONSTRAINT devices_capabilities_object CHECK (jsonb_typeof(capabilities) = 'object')
                );
                ALTER TABLE jellyfin.devices
                    DROP CONSTRAINT IF EXISTS devices_app_name_not_empty;
                CREATE UNIQUE INDEX IF NOT EXISTS devices_access_token_key
                    ON jellyfin.devices (access_token);
                CREATE INDEX IF NOT EXISTS devices_device_activity_idx
                    ON jellyfin.devices (device_id, date_last_activity DESC);
                CREATE INDEX IF NOT EXISTS devices_user_device_idx
                    ON jellyfin.devices (user_id, device_id);
                ",
            )
            .await?;
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .get_connection()
            .execute_unprepared(
                r"
                DROP TABLE IF EXISTS jellyfin.devices CASCADE;
                DROP TABLE IF EXISTS jellyfin.api_keys CASCADE;
                ",
            )
            .await?;
        Ok(())
    }
}
