[package]
name = "jellyfin-server"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
jellyfin-api = { path = "../jellyfin-api" }
jellyfin-controller = { path = "../jellyfin-controller" }
jellyfin-data = { path = "../jellyfin-data" }
jellyfin-live-tv = { path = "../jellyfin-live-tv" }
jellyfin-media-encoding = { path = "../jellyfin-media-encoding" }
jellyfin-networking = { path = "../jellyfin-networking" }
sea-orm.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
